// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACaTtgrvdZftfulcN3zGNTVcCn-DTqAOM',
    appId: '1:823039614157:web:06ea2bad87807349695d84',
    messagingSenderId: '823039614157',
    projectId: 'sgard-d50cf',
    authDomain: 'sgard-d50cf.firebaseapp.com',
    storageBucket: 'sgard-d50cf.firebasestorage.app',
    measurementId: 'G-4TEBFSMCYT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvH6sk7PACkQzshMtpGxKw5elpmLNQszE',
    appId: '1:823039614157:android:fc0319d672cea0db695d84',
    messagingSenderId: '823039614157',
    projectId: 'sgard-d50cf',
    storageBucket: 'sgard-d50cf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAJ9YwjqRIYSjbNQJpcmDrKwaAKJwJ4mI',
    appId: '1:823039614157:ios:12b3fed27f767263695d84',
    messagingSenderId: '823039614157',
    projectId: 'sgard-d50cf',
    storageBucket: 'sgard-d50cf.firebasestorage.app',
    iosBundleId: 'com.example.proyectofinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAJ9YwjqRIYSjbNQJpcmDrKwaAKJwJ4mI',
    appId: '1:823039614157:ios:12b3fed27f767263695d84',
    messagingSenderId: '823039614157',
    projectId: 'sgard-d50cf',
    storageBucket: 'sgard-d50cf.firebasestorage.app',
    iosBundleId: 'com.example.proyectofinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACaTtgrvdZftfulcN3zGNTVcCn-DTqAOM',
    appId: '1:823039614157:web:b69c789166562bc9695d84',
    messagingSenderId: '823039614157',
    projectId: 'sgard-d50cf',
    authDomain: 'sgard-d50cf.firebaseapp.com',
    storageBucket: 'sgard-d50cf.firebasestorage.app',
    measurementId: 'G-TFDE0S0H28',
  );
}
